name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 --version
      - name: Instalar Black
        run: python3 -m pip install black
      - name: Formatar código
        run: python3 -m black --check .
      - run: python3 -m py_compile function_app.py